import { DEFAULT_INSPECTION_PDF_LAYOUT, type PdfKitDocument } from '../pdf-generator.js'
import { embedPhotoEvidencePages } from './inspection-report.js'

export type DeficiencyReportTemplateOptions = {
  organizationName: string
  accentColor: string
  bodyFont: string
}

export const DEFAULT_DEFICIENCY_REPORT_TEMPLATE_OPTIONS: DeficiencyReportTemplateOptions = {
  // Neutral placeholder for the deploying agency (the official inspecting authority).
  // Override per deployment; not the product brand.
  organizationName: 'Inspection Authority',
  accentColor: '#7c2d12',
  bodyFont: DEFAULT_INSPECTION_PDF_LAYOUT.bodyFont,
}

export type DeficiencyReportTemplateContext = {
  deficiencyId: string
  recordedBy: string
  severity: string
  status: string
  description: string
  location: string | null
  permitLine: string | null
  documentHash: string
  qrPng: Buffer
  evidencePhotoBuffers: Buffer[]
}

export function renderDeficiencyReportTemplate(
  doc: PdfKitDocument,
  ctx: DeficiencyReportTemplateContext,
  opts?: Partial<DeficiencyReportTemplateOptions>,
): void {
  const o = { ...DEFAULT_DEFICIENCY_REPORT_TEMPLATE_OPTIONS, ...opts }
  doc.font(o.bodyFont)

  doc
    .fontSize(10)
    .fillColor(o.accentColor)
    .text(o.organizationName.toUpperCase(), { align: 'center' })
  doc.fontSize(16).fillColor('#000000').text('Deficiency Report', { align: 'center' })
  doc.fontSize(9).fillColor('#444444').text('Scoped deficiency record', { align: 'center' })
  doc.moveDown(0.85)

  doc.fontSize(11).fillColor('#000000')
  doc.text(`Deficiency ID: ${ctx.deficiencyId}`)
  doc.text(`Recorded by: ${ctx.recordedBy}`)
  doc.text(`Severity: ${ctx.severity} — Status: ${ctx.status}`)
  doc.moveDown(0.45)

  doc.fontSize(12).fillColor(o.accentColor).text('Description', { underline: true })
  doc.fontSize(10).fillColor('#000000').text(ctx.description)
  if (ctx.location) {
    doc.moveDown(0.35)
    doc.text(`Location: ${ctx.location}`)
  }
  doc.moveDown(0.65)

  if (ctx.permitLine) {
    doc.fontSize(12).fillColor(o.accentColor).text('Related permit', { underline: true })
    doc.fontSize(10).fillColor('#000000').text(ctx.permitLine)
    doc.moveDown(0.55)
  }

  embedPhotoEvidencePages(doc, 'Evidence photos', ctx.evidencePhotoBuffers)

  doc.addPage()
  doc.fontSize(12).fillColor(o.accentColor).text('Record integrity', { underline: true })
  doc.fontSize(9).fillColor('#000000')
  doc.text(`Document hash (SHA-256): ${ctx.documentHash}`)
  doc.moveDown(0.5)
  doc.image(ctx.qrPng, { fit: [100, 100] })
  doc.moveDown(0.35)
  doc
    .fontSize(8)
    .fillColor('#444444')
    .text('Generated by CodeComply in alignment with Alberta Safety Codes Act requirements.')
  doc.fillColor('#000000')
}
