import { DEFAULT_INSPECTION_PDF_LAYOUT, type PdfKitDocument } from '../pdf-generator.js'
import { embedPhotoEvidencePages } from './inspection-report.js'

export type StopWorkOrderTemplateOptions = {
  organizationName: string
  accentColor: string
  bodyFont: string
}

export const DEFAULT_STOP_WORK_ORDER_TEMPLATE_OPTIONS: StopWorkOrderTemplateOptions = {
  // Neutral placeholder for the deploying agency (the official inspecting authority).
  // Override per deployment; not the product brand.
  organizationName: 'Inspection Authority',
  accentColor: '#991b1b',
  bodyFont: DEFAULT_INSPECTION_PDF_LAYOUT.bodyFont,
}

export type StopWorkOrderTemplateContext = {
  orderRecordId: string
  inspectorName: string
  designation: string | null
  permitLine: string | null
  issuedAtIso: string
  deficiencyDescription: string
  location: string | null
  documentHash: string
  qrPng: Buffer
  evidencePhotoBuffers: Buffer[]
}

export function renderStopWorkOrderTemplate(
  doc: PdfKitDocument,
  ctx: StopWorkOrderTemplateContext,
  opts?: Partial<StopWorkOrderTemplateOptions>,
): void {
  const o = { ...DEFAULT_STOP_WORK_ORDER_TEMPLATE_OPTIONS, ...opts }
  doc.font(o.bodyFont)

  doc
    .fontSize(10)
    .fillColor(o.accentColor)
    .text(o.organizationName.toUpperCase(), { align: 'center' })
  doc.fontSize(16).fillColor('#000000').text('Section 49 — Stop Work Order', { align: 'center' })
  doc.fontSize(9).fillColor('#444444').text('Official stop work directive', { align: 'center' })
  doc.moveDown(0.85)

  doc.fontSize(11).fillColor('#000000')
  doc.text(`Order record ID: ${ctx.orderRecordId}`)
  doc.text(`Inspector: ${ctx.inspectorName}`)
  if (ctx.designation) doc.text(`Designation: ${ctx.designation}`)
  doc.text(`Issued: ${ctx.issuedAtIso}`)
  doc.moveDown(0.45)

  if (ctx.permitLine) {
    doc.fontSize(12).fillColor(o.accentColor).text('Permit / site', { underline: true })
    doc.fontSize(10).fillColor('#000000').text(ctx.permitLine)
    doc.moveDown(0.55)
  }

  doc.fontSize(12).fillColor(o.accentColor).text('Stop work basis', { underline: true })
  doc.fontSize(10).fillColor('#000000').text(ctx.deficiencyDescription)
  if (ctx.location) {
    doc.moveDown(0.35)
    doc.text(`Location: ${ctx.location}`)
  }
  doc.moveDown(0.65)

  embedPhotoEvidencePages(doc, 'Evidence photos', ctx.evidencePhotoBuffers)

  doc.addPage()
  doc.fontSize(12).fillColor(o.accentColor).text('Record integrity', { underline: true })
  doc.fontSize(9).fillColor('#000000')
  doc.text(`Document hash (SHA-256): ${ctx.documentHash}`)
  doc.moveDown(0.5)
  doc.image(ctx.qrPng, { fit: [100, 100] })
  doc.moveDown(0.35)
  doc
    .fontSize(8)
    .fillColor('#444444')
    .text('Generated by CodeComply in alignment with Alberta Safety Codes Act requirements.')
  doc.fillColor('#000000')
}
