/**
 * M11-S22 — Writes apps/api/openapi.yaml from live GET /openapi.json.
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'
import { stringify } from 'yaml'
import { app } from '../src/app.js'

const API_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUTPUT = join(API_ROOT, 'openapi.yaml')

describe('Export OpenAPI YAML (M11-S22)', () => {
  it('writes openapi.yaml from live spec', async () => {
    const res = await app.request('/openapi.json')
    expect(res.status).toBe(200)
    const spec = await res.json()

    const header = `# CodeComply Connect API — OpenAPI 3.0
# Generated by scripts/export-openapi.mjs (M11-S22). Do not edit by hand; re-export after route changes.
# Interactive docs: GET /swagger (Swagger UI) · JSON: GET /openapi.json

`
    const yaml = header + stringify(spec, { lineWidth: 120 })
    writeFileSync(OUTPUT, yaml, 'utf8')

    expect(yaml).toContain('openapi: 3.0.0')
    expect(yaml).toContain('bearerAuth')
    expect(Object.keys(spec.paths).length).toBeGreaterThan(30)
  })
})
