import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    sequence: { concurrent: false },
    poolOptions: {
      threads: { singleThread: true },
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: [
        'src/services/audit-log.service.ts',
        'src/services/checklist.service.ts',
        'src/services/code-library.service.ts',
        'src/services/deficiency.service.ts',
        'src/services/document.service.ts',
        'src/mappers/checklist.mapper.ts',
        'src/mappers/deficiency.mapper.ts',
        'src/mappers/document.mapper.ts',
        'src/routes/checklists.ts',
        'src/routes/codes.ts',
        'src/routes/deficiencies.ts',
        'src/routes/documents.ts',
        'src/routes/reports.ts',
        'src/routes/voc.ts',
        'src/mappers/report.mapper.ts',
        'src/mappers/voc.mapper.ts',
        'src/lib/storage/storage-client.ts',
        'src/lib/email/email-service.ts',
        'src/lib/email/email-transport.ts',
        'src/lib/pdf/pdf-generator.ts',
        'src/lib/pdf/pdf-image-prep.ts',
        'src/lib/pdf/pdf-generation-runner.ts',
        'src/lib/pdf/pdf-generation-config.ts',
        'src/lib/load-test/load-test-config.ts',
        'src/lib/load-test/load-test-metrics.ts',
        'src/lib/load-test/load-test-runner.ts',
        'src/services/report.service.ts',
        'src/services/voc.service.ts',
        'src/services/distribution.service.ts',
        'src/services/inspection.service.ts',
        'src/middleware/immutable.ts',
        'src/lib/pdf/templates/inspection-report.ts',
        'src/lib/pdf/templates/deficiency-report.ts',
        'src/lib/pdf/templates/no-entry-letter.ts',
      ],
      exclude: ['**/*.spec.ts', '**/*.d.ts', '**/node_modules/**', '**/dist/**'],
      thresholds: {
        lines: 90,
        statements: 90,
        functions: 90,
        branches: 75,
      },
    },
  },
})
